# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import (
    TypeVar,
    Generic,
    Union,
    Optional,
    Protocol,
    Tuple,
    List,
    Any,
    Self,
    Callable,
)
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_http_types_0_2_10


class HttpHandler(Protocol):

    @abstractmethod
    def handle_request(
        self,
        request: wasi_http_types_0_2_10.IncomingRequest,
        response_out: wasi_http_types_0_2_10.ResponseOutparam,
    ) -> None:
        """
        Plugin must implement this function to handle HTTP requests
        """
        raise NotImplementedError
