# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import (
    TypeVar,
    Generic,
    Union,
    Optional,
    Protocol,
    Tuple,
    List,
    Any,
    Self,
    Callable,
)
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_io_poll_0_2_10


def now() -> int:
    raise NotImplementedError


def resolution() -> int:
    raise NotImplementedError


def subscribe_instant(when: int) -> wasi_io_poll_0_2_10.Pollable:
    raise NotImplementedError


def subscribe_duration(when: int) -> wasi_io_poll_0_2_10.Pollable:
    raise NotImplementedError
