# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import (
    TypeVar,
    Generic,
    Union,
    Optional,
    Protocol,
    Tuple,
    List,
    Any,
    Self,
    Callable,
)
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class ConnectionConfig:
    """
    Config defines settings to open connection
    """

    def __init__(self, connection_string: str) -> None:
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class Error_TypeError:
    value: str


@dataclass
class Error_ServerError:
    value: str


@dataclass
class Error_Other:
    value: str


Error = Union[Error_TypeError, Error_ServerError, Error_Other]
"""
Errors interacting with Redis
"""


@dataclass
class RedisArgument_I64:
    value: int


@dataclass
class RedisArgument_Str:
    value: str


RedisArgument = Union[RedisArgument_I64, RedisArgument_Str]
"""
Arguent of `execute` method
"""


@dataclass
class Attribute:
    """
    Attribute value from the server.
    """

    data: Any
    attributes: List[Tuple[Any, Any]]


@dataclass
class VerbatimFormat_Unknown:
    value: str


@dataclass
class VerbatimFormat_Markdown:
    pass


@dataclass
class VerbatimFormat_Text:
    pass


VerbatimFormat = Union[
    VerbatimFormat_Unknown, VerbatimFormat_Markdown, VerbatimFormat_Text
]
"""
`VerbatimString`'s format types defined by spec
"""


@dataclass
class VerbatimString:
    """
    First String is format and other is the string
    """

    format: VerbatimFormat
    text: str


@dataclass
class PushKind_Disconnection:
    pass


@dataclass
class PushKind_Other:
    value: str


@dataclass
class PushKind_Invalidate:
    pass


@dataclass
class PushKind_Message:
    pass


@dataclass
class PushKind_Pmessage:
    pass


@dataclass
class PushKind_Smessage:
    pass


@dataclass
class PushKind_Unsubscribe:
    pass


@dataclass
class PushKind_Punsubscribe:
    pass


@dataclass
class PushKind_Sunsubscribe:
    pass


@dataclass
class PushKind_Subscribe:
    pass


@dataclass
class PushKind_Psubscribe:
    pass


@dataclass
class PushKind_Ssubscribe:
    pass


PushKind = Union[
    PushKind_Disconnection,
    PushKind_Other,
    PushKind_Invalidate,
    PushKind_Message,
    PushKind_Pmessage,
    PushKind_Smessage,
    PushKind_Unsubscribe,
    PushKind_Punsubscribe,
    PushKind_Sunsubscribe,
    PushKind_Subscribe,
    PushKind_Psubscribe,
    PushKind_Ssubscribe,
]
"""
`Push` type's currently known kinds.
"""


@dataclass
class Push:
    """
    Push data from the server.
    """

    kind: PushKind
    data: List[Any]


@dataclass
class RedisValue_Nil:
    pass


@dataclass
class RedisValue_Int:
    value: int


@dataclass
class RedisValue_BulkString:
    value: bytes


@dataclass
class RedisValue_Array:
    value: List[Any]


@dataclass
class RedisValue_SimpleString:
    value: str


@dataclass
class RedisValue_Okay:
    pass


@dataclass
class RedisValue_Map:
    value: List[Tuple[Any, Any]]


@dataclass
class RedisValue_Attribute:
    value: Attribute


@dataclass
class RedisValue_Set:
    value: List[Any]


@dataclass
class RedisValue_Double:
    value: float


@dataclass
class RedisValue_Boolean:
    value: bool


@dataclass
class RedisValue_VerbatimString:
    value: VerbatimString


@dataclass
class RedisValue_BigNumber:
    value: str


@dataclass
class RedisValue_Push:
    value: Push


RedisValue = Union[
    RedisValue_Nil,
    RedisValue_Int,
    RedisValue_BulkString,
    RedisValue_Array,
    RedisValue_SimpleString,
    RedisValue_Okay,
    RedisValue_Map,
    RedisValue_Attribute,
    RedisValue_Set,
    RedisValue_Double,
    RedisValue_Boolean,
    RedisValue_VerbatimString,
    RedisValue_BigNumber,
    RedisValue_Push,
]
"""
Redis value
"""


class LazyRedisValue:
    """
    Recursive redis value
    """

    def __init__(self, value: RedisValue) -> None:
        raise NotImplementedError

    @classmethod
    def get(cls, value: Self) -> RedisValue:
        """
        Consume resource and get inner value
        """
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Connection:
    """
    A connection to a Redis instance
    """

    @classmethod
    def open(cls, config: ConnectionConfig) -> Self:
        """
        Open a connection to the Redis instance

        Raises: `componentize_py_types.Err(wassel_sdk.wit.imports.wassel_redis_redis.Error)`
        """
        raise NotImplementedError

    def execute(self, command: str, arguments: List[RedisArgument]) -> RedisValue:
        """
        Execute an arbitrary Redis command and receive the result.

        Raises: `componentize_py_types.Err(wassel_sdk.wit.imports.wassel_redis_redis.Error)`
        """
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError
