# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import (
    TypeVar,
    Generic,
    Union,
    Optional,
    Protocol,
    Tuple,
    List,
    Any,
    Self,
    Callable,
)
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import wasi_http_types_0_2_10


def send(
    url: str, req: wasi_http_types_0_2_10.OutgoingRequest
) -> wasi_http_types_0_2_10.IncomingResponse:
    """
    Send outbound HTTP request and get incoming response

    Raises: `componentize_py_types.Err(wassel_sdk.wit.imports.wasi_http_types_0_2_10.ErrorCode)`
    """
    raise NotImplementedError
