# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import (
    TypeVar,
    Generic,
    Union,
    Optional,
    Protocol,
    Tuple,
    List,
    Any,
    Self,
    Callable,
)
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class ConnectionConfig:
    """
    Config defines settings to open connection
    """

    def __init__(self, connection_string: str) -> None:
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class Severity_Panic:
    pass


@dataclass
class Severity_Fatal:
    pass


@dataclass
class Severity_Error:
    pass


@dataclass
class Severity_Warning:
    pass


@dataclass
class Severity_Notice:
    pass


@dataclass
class Severity_Debug:
    pass


@dataclass
class Severity_Info:
    pass


@dataclass
class Severity_Log:
    pass


Severity = Union[
    Severity_Panic,
    Severity_Fatal,
    Severity_Error,
    Severity_Warning,
    Severity_Notice,
    Severity_Debug,
    Severity_Info,
    Severity_Log,
]
"""
Postgres error severity
"""


@dataclass
class ErrorPositionInternal:
    """
    A position in an internally generated query.
    """

    position: int
    query: str


@dataclass
class ErrorPosition_Original:
    value: int


@dataclass
class ErrorPosition_Internal:
    value: ErrorPositionInternal


ErrorPosition = Union[ErrorPosition_Original, ErrorPosition_Internal]
"""
Represents the position of an error in a query.
"""


@dataclass
class DatabaseError:
    """
    Postgres error
    """

    severity: str
    parsed_severity: Optional[Severity]
    code: str
    message: str
    detail: Optional[str]
    hint: Optional[str]
    position: Optional[ErrorPosition]
    where: Optional[str]
    schema: Optional[str]
    table: Optional[str]
    column: Optional[str]
    datatype: Optional[str]
    constraint: Optional[str]
    file: Optional[str]
    line: Optional[int]
    routine: Optional[str]


@dataclass
class Error_Database:
    value: DatabaseError


@dataclass
class Error_Query:
    value: str


@dataclass
class Error_Other:
    value: str


Error = Union[Error_Database, Error_Query, Error_Other]
"""
Generic error
"""


@dataclass
class Uuid:
    """
    Postgres UUID
    """

    d1: int
    d2: int
    d3: int
    d4: int


@dataclass
class Date:
    """
    Postgres date
    """

    year: int
    month: int
    day: int


@dataclass
class Time:
    """
    Postgres time
    """

    hour: int
    minute: int
    second: int
    nanosecond: int


@dataclass
class Datetime:
    """
    Postgres datetime
    """

    date: Date
    time: Time
    offset: Optional[int]


@dataclass
class Interval:
    """
    Postgres interval
    """

    months: int
    days: int
    microseconds: int


class RangeBound(Enum):
    """
    Postgres range bound kind
    """

    INCLUDED = 0
    EXCLUDED = 1
    UNBOUNDED = 2


@dataclass
class RangeInt32:
    """
    Postgres range of int32
    """

    begin: Optional[int]
    begin_bound: RangeBound
    end: Optional[int]
    end_bound: RangeBound


@dataclass
class RangeInt64:
    """
    Postgres range of int64
    """

    begin: Optional[int]
    begin_bound: RangeBound
    end: Optional[int]
    end_bound: RangeBound


@dataclass
class RangeDecimal:
    """
    Postgres range of decimal
    """

    begin: Optional[str]
    begin_bound: RangeBound
    end: Optional[str]
    end_bound: RangeBound


@dataclass
class Point:
    """
    Postgres point
    """

    x: float
    y: float


@dataclass
class Circle:
    """
    Postgres circle
    """

    x: float
    y: float
    radius: float


@dataclass
class Line:
    """
    Postgres line
    """

    a: float
    b: float
    c: float


@dataclass
class LineSegment:
    """
    Postgres line segment
    """

    start: Point
    end: Point


@dataclass
class Path:
    """
    Postgres path
    """

    closed: bool
    points: List[Point]


@dataclass
class Polygon:
    """
    Postgres polygon
    """

    points: List[Point]


@dataclass
class Cube_Point:
    value: float


@dataclass
class Cube_ZeroVolume:
    value: List[float]


@dataclass
class Cube_OneDimensionInterval:
    value: Tuple[float, float]


@dataclass
class Cube_MultiDimensional:
    value: List[List[float]]


Cube = Union[
    Cube_Point, Cube_ZeroVolume, Cube_OneDimensionInterval, Cube_MultiDimensional
]
"""
Postgres cube
"""


@dataclass
class Value_Boolean:
    value: bool


@dataclass
class Value_Int16:
    value: int


@dataclass
class Value_Int32:
    value: int


@dataclass
class Value_Int64:
    value: int


@dataclass
class Value_Float32:
    value: float


@dataclass
class Value_Float64:
    value: float


@dataclass
class Value_Decimal:
    value: str


@dataclass
class Value_Money:
    value: int


@dataclass
class Value_Uuid:
    value: Uuid


@dataclass
class Value_Text:
    value: str


@dataclass
class Value_Binary:
    value: bytes


@dataclass
class Value_Date:
    value: Date


@dataclass
class Value_Time:
    value: Time


@dataclass
class Value_Datetime:
    value: Datetime


@dataclass
class Value_Interval:
    value: Interval


@dataclass
class Value_RangeInt32:
    value: RangeInt32


@dataclass
class Value_RangeInt64:
    value: RangeInt64


@dataclass
class Value_RangeDecimal:
    value: RangeDecimal


@dataclass
class Value_ArrayInt32:
    value: List[Optional[int]]


@dataclass
class Value_ArrayInt64:
    value: List[Optional[int]]


@dataclass
class Value_ArrayDecimal:
    value: List[Optional[str]]


@dataclass
class Value_ArrayStr:
    value: List[Optional[str]]


@dataclass
class Value_Jsonb:
    value: bytes


@dataclass
class Value_Hstore:
    value: List[Tuple[str, Optional[str]]]


@dataclass
class Value_Point:
    value: Point


@dataclass
class Value_Circle:
    value: Circle


@dataclass
class Value_Line:
    value: Line


@dataclass
class Value_LineSegment:
    value: LineSegment


@dataclass
class Value_Path:
    value: Path


@dataclass
class Value_Polygon:
    value: Polygon


@dataclass
class Value_Cube:
    value: Cube


@dataclass
class Value_PgNull:
    pass


@dataclass
class Value_Other:
    value: bytes


Value = Union[
    Value_Boolean,
    Value_Int16,
    Value_Int32,
    Value_Int64,
    Value_Float32,
    Value_Float64,
    Value_Decimal,
    Value_Money,
    Value_Uuid,
    Value_Text,
    Value_Binary,
    Value_Date,
    Value_Time,
    Value_Datetime,
    Value_Interval,
    Value_RangeInt32,
    Value_RangeInt64,
    Value_RangeDecimal,
    Value_ArrayInt32,
    Value_ArrayInt64,
    Value_ArrayDecimal,
    Value_ArrayStr,
    Value_Jsonb,
    Value_Hstore,
    Value_Point,
    Value_Circle,
    Value_Line,
    Value_LineSegment,
    Value_Path,
    Value_Polygon,
    Value_Cube,
    Value_PgNull,
    Value_Other,
]
"""
Postgres value
"""


@dataclass
class DataType_Boolean:
    pass


@dataclass
class DataType_Int16:
    pass


@dataclass
class DataType_Int32:
    pass


@dataclass
class DataType_Int64:
    pass


@dataclass
class DataType_Float32:
    pass


@dataclass
class DataType_Float64:
    pass


@dataclass
class DataType_Decimal:
    pass


@dataclass
class DataType_Money:
    pass


@dataclass
class DataType_Uuid:
    pass


@dataclass
class DataType_Text:
    pass


@dataclass
class DataType_Binary:
    pass


@dataclass
class DataType_Date:
    pass


@dataclass
class DataType_Time:
    pass


@dataclass
class DataType_Datetime:
    pass


@dataclass
class DataType_Interval:
    pass


@dataclass
class DataType_RangeInt32:
    pass


@dataclass
class DataType_RangeInt64:
    pass


@dataclass
class DataType_RangeDecimal:
    pass


@dataclass
class DataType_ArrayInt32:
    pass


@dataclass
class DataType_ArrayInt64:
    pass


@dataclass
class DataType_ArrayDecimal:
    pass


@dataclass
class DataType_ArrayStr:
    pass


@dataclass
class DataType_Jsonb:
    pass


@dataclass
class DataType_Hstore:
    pass


@dataclass
class DataType_Point:
    pass


@dataclass
class DataType_Circle:
    pass


@dataclass
class DataType_Line:
    pass


@dataclass
class DataType_LineSegment:
    pass


@dataclass
class DataType_Path:
    pass


@dataclass
class DataType_Polygon:
    pass


@dataclass
class DataType_Cube:
    pass


@dataclass
class DataType_PgNull:
    pass


@dataclass
class DataType_Other:
    value: str


DataType = Union[
    DataType_Boolean,
    DataType_Int16,
    DataType_Int32,
    DataType_Int64,
    DataType_Float32,
    DataType_Float64,
    DataType_Decimal,
    DataType_Money,
    DataType_Uuid,
    DataType_Text,
    DataType_Binary,
    DataType_Date,
    DataType_Time,
    DataType_Datetime,
    DataType_Interval,
    DataType_RangeInt32,
    DataType_RangeInt64,
    DataType_RangeDecimal,
    DataType_ArrayInt32,
    DataType_ArrayInt64,
    DataType_ArrayDecimal,
    DataType_ArrayStr,
    DataType_Jsonb,
    DataType_Hstore,
    DataType_Point,
    DataType_Circle,
    DataType_Line,
    DataType_LineSegment,
    DataType_Path,
    DataType_Polygon,
    DataType_Cube,
    DataType_PgNull,
    DataType_Other,
]
"""
Postgres data type
"""


@dataclass
class Column:
    """
    Table column
    """

    name: str
    data_type: DataType


@dataclass
class RowSet:
    """
    Set of rows
    """

    columns: List[Column]
    rows: List[List[Value]]


class Connection:
    """
    A connection to a postgres database
    """

    @classmethod
    def open(cls, config: ConnectionConfig) -> Self:
        """
        Open a connection to the database

        Raises: `componentize_py_types.Err(wassel_sdk.wit.imports.wassel_postgres_postgres.Error)`
        """
        raise NotImplementedError

    def query(self, sql: str, params: List[Value]) -> RowSet:
        """
        Query the database

        Raises: `componentize_py_types.Err(wassel_sdk.wit.imports.wassel_postgres_postgres.Error)`
        """
        raise NotImplementedError

    def execute(self, sql: str, params: List[Value]) -> int:
        """
        Execute statement on the database

        Raises: `componentize_py_types.Err(wassel_sdk.wit.imports.wassel_postgres_postgres.Error)`
        """
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError
